version: '3'
services:
  # Shell command =>  mongo -u mongoadminsusr -p mongoadminpassword
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadminsusr
      MONGO_INITDB_ROOT_PASSWORD: mongoadminpassword
      MONGO_INITDB_DATABASE: mydb
    ports:
      - '27017:27017'
    networks:
      - node-network

  mongo_db_admin:
    image: mongo-express:latest
    container_name: mongo_db_admin
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_USERNAME=mongoadminsusr
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongoadminpassword
      - ME_CONFIG_MONGODB_URL=mongodb://mongoadminsusr:mongoadminpassword@mongodb:27017/mydb?ssl=false&authSource=admin&directConnection=true
    networks:
      - node-network
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb

networks:
  node-network:
    driver: bridge
